change

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,6 +46,22 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Generate environment.override.ts
+        run: |
+          node prebuild.mjs
+
+      - name: Check environment.override.ts file
+        run: |
+          FILE=src/main/webapp/app/environments/environment.override.ts
+          if [ -f "$FILE" ]; then
+            echo "✅ environment.override.ts found."
+            echo "🔍 Showing content (first 3 lines):"
+            head -n 3 "$FILE"
+          else
+            echo "❌ environment.override.ts not found."
+            exit 1
+          fi
+
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -65,15 +81,3 @@ jobs:
             KEYCLOAK_REALM=${{ vars.KEYCLOAK_REALM }}
             KEYCLOAK_CLIENT_ID=${{ vars.KEYCLOAK_CLIENT_ID }}
             KEYCLOAK_ENABLE_LOGGING=${{ vars.KEYCLOAK_ENABLE_LOGGING }}
-
-      - name: Check environment.override.ts file
-        run: |
-          FILE=src/main/webapp/app/environments/environment.override.ts
-          if [ -f "$FILE" ]; then
-            echo "✅ environment.override.ts found."
-            echo "🔍 Showing content (first 3 lines):"
-            head -n 3 "$FILE"
-          else
-            echo "❌ environment.override.ts not found."
-            exit 1
-          fi
