test environemnt override

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,3 +65,15 @@ jobs:
             KEYCLOAK_REALM=${{ vars.KEYCLOAK_REALM }}
             KEYCLOAK_CLIENT_ID=${{ vars.KEYCLOAK_CLIENT_ID }}
             KEYCLOAK_ENABLE_LOGGING=${{ vars.KEYCLOAK_ENABLE_LOGGING }}
+
+      - name: Check environment.override.ts file
+        run: |
+          FILE=src/main/webapp/app/environments/environment.override.ts
+          if [ -f "$FILE" ]; then
+            echo "✅ environment.override.ts found."
+            echo "🔍 Showing content (first 3 lines):"
+            head -n 3 "$FILE"
+          else
+            echo "❌ environment.override.ts not found."
+            exit 1
+          fi
